name: Run evaluation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # TODO(@gussmith23) It would be nice if this wasn't necessary
  cleaner:
    runs-on: self-hosted
    steps:
      - name: Clean up previous runs
        run: rm -rf "${{ github.workspace }}"

  run-evaluation:
    # Make sure we clean first.
    needs: cleaner

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.PAT }}
        ssh-key: ${{ secrets.SSH_KEY }}

    - name: Build Docker image
      run: docker build --no-cache=true --tag lakeroad-evaluation .
    - name: Build the Docker image
      id: build
      run: |
        export TAG=lakeroad-evaluation:$(date +%s)
        echo "::set-output name=TAG::$TAG"
        docker build \
          . \
          --file Dockerfile \
          --tag $TAG
    - name: Run evaluation
      run: docker run ${{ steps.build.outputs.TAG }}
